// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8zhgK7F_CYrhSWeH9p9ap3cjRCfhIbU4',
    appId: '1:1016879536664:web:f1fc3fd01fd68c4a9c816d',
    messagingSenderId: '1016879536664',
    projectId: 'opencarssooq',
    authDomain: 'opencarssooq.firebaseapp.com',
    storageBucket: 'opencarssooq.appspot.com',
    measurementId: 'G-TYMLRCFHBL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtfx6PdczRNRMrKsA6O9zuUnfn4jyvLFM',
    appId: '1:1016879536664:android:c658476d456d14e29c816d',
    messagingSenderId: '1016879536664',
    projectId: 'opencarssooq',
    storageBucket: 'opencarssooq.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIj8Yc6lAor9DxFRW5lz1aynyHyV54v-s',
    appId: '1:1016879536664:ios:a59a5dd34efb9dba9c816d',
    messagingSenderId: '1016879536664',
    projectId: 'opencarssooq',
    storageBucket: 'opencarssooq.appspot.com',
    iosClientId: '1016879536664-0jacpenj7b6djs3bnsv6c321cg8eisus.apps.googleusercontent.com',
    iosBundleId: 'com.iug.opencarssooq',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIj8Yc6lAor9DxFRW5lz1aynyHyV54v-s',
    appId: '1:1016879536664:ios:a59a5dd34efb9dba9c816d',
    messagingSenderId: '1016879536664',
    projectId: 'opencarssooq',
    storageBucket: 'opencarssooq.appspot.com',
    iosClientId: '1016879536664-0jacpenj7b6djs3bnsv6c321cg8eisus.apps.googleusercontent.com',
    iosBundleId: 'com.iug.opencarssooq',
  );

  /*
  web       1:1016879536664:web:f1fc3fd01fd68c4a9c816d
android   1:1016879536664:android:c658476d456d14e29c816d
ios       1:1016879536664:ios:a59a5dd34efb9dba9c816d
macos     1:1016879536664:ios:a59a5dd34efb9dba9c816d

   */
}
