import 'text_language_keys.dart';

Map<String, String> english = {

  signUp : "Sign Up",
  name : "Name ",
  enterStoreName : "Enter store name",
  phone : "Phone ",
  enterStorePhoneNumber : "Enter store phone number",
  address  : "Address",
  enterStoreAddress : "Enter store address",
  state : "State",
  choose : "-choose-",
  thisFieldIsRequired : "this field is required",
  facebook : "Facebook",
  enterStoreFacebookUrl : "Enter store facebook url",
  instegram : "Instegram",
  enterStoreInstegramUrl : "Enter store instegram url",
  whatsapp : "whatsapp",
  enterStoreWhatsappUrl : "Enter store whatsapp number",
  registerAccount : "Register Account",
  signUpWithYourInfo : "Sign up with your Info",
  enterYourName : "Enter your name",
  email : "Email",
  enterYourEmail : "Enter your email",
  enterYourPhoneNumber : "Enter your phone number",
  enterYourAddress : "Enter your address",
  password : "Password",
  enterYourPassword : "Enter your password",
  confirmPassword : "Confirm Password",
  re_enterYourPassword : "Re-enter your password",
  imAVendor : "I'm a vendor",
  signIn : "Sign In",
  welcomeBack : "Welcome Back",
  signInWithYourEmailAndPassword : "Sign in with your email and password",
  rememberMe : "Remember me",
  forgetPassword : "Forgot Password",
  dontHaveAccount : "Don’t have an account ?",
  titleForgotPassword : "Please enter your phone and we will send \n you a link to return to your account",
  Continue : "Continue",
  otpVerification : "OTP Verification",
  weSentYourCodeTo : "We sent your code to",
  thisCodeWillExpiredIn : "This code will expired in",
  resendOtpCode : "Resend OTP Code",
  pleaseEnterYourNewPassword : "Please enter your new password",
  enterNewPassword : "Enter new password",
  re_enterNewPassword : "Re-enter new password",
  addCar : "Add Car",
  enterCarName : "Enter car name",
  enterCarPrice : "Enter car price",
  price : "Price",
  enterCarDescription : "Enter car description",
  description : "Description",
  save : "Save",
  addOffer : "Add Offer",
  oldPrice : "Old price:",
  enterCarNewPrice : "Enter car new price",
  newPrice : "New Price",
  discountPercentage : "Discount Percentage:",
  feedback : "Feedback",
  addYourComment : "Add your comment",
  comment : "Comment",
  submit : "Submit",
  callTheStore : "Call The Store",
  updateCar : "Update Car",
  Update : "Update",
  updateOffer : "Update Offer",
  updateStore : "Update Store",
  language : "Language",
  chooseLang : "Choose language",
  ar: "Arabic",
  en: "English",
  helpCenter : "Help Center",
  faq : "FAQ",
  helpCenter1 : "How does warranty work on store?",
  helpCenter2 : "How long is my order delivery time?",
  helpCenter3 : "How to become a store seller?",
  helpCenter4 : "Why I don't accept otp on my phone?",
  helpCenter5 : "How to rate my order products?",
  contactUs : "Contact Us",
  chatUsNow : "Chat us now",
  chatHere : "You can chat with us here",
  profile : "Profile",
  enterNewName : "Enter new name",
  enterNewEmail : "Enter new email",
  enterNewPhoneNumber : "Enter new phone number",
  enterNewAddress : "Enter new address",
  saveChanges : "Save Changes",
  cars : "Cars",
  rateStore : "Rate Store",
  favorites : "Favorites",
  bestSeller : "Best Seller",
  newCars : "New Cars",
  offers : "Offers",
  searchCars : "Search cars",
  titleSearchCars : "You can search about any car",
  searchCarsAndStores : "You can search about cars and stores",
  settings : "Settings",
  myAccount : "My Account",
  myStore : "My Store",
  logOut : "Log Out",
  chooseImagesForCar : "Please choose images for car",
  deletedOfferSuccessfully : "Deleted offer successfully",
  emailNotFound : "email not found!!",
  emailOrPasswordNotCorrect : "email or password not correct",
  otpNumberIsNotCorrect : "otp number is not correct!",
  otpNumberExpired : "otp number has been expired!!",
  blockedAllRequests : "We have blocked all requests from this device due to unusual activity",
  passwordAndRePasswordNotMatched : "Password and Re password not matched!",
  chooseLogoForStore : "Please choose logo for store",
  thisLinkIsEmpty : "this link is empty!",
  deletedCarOfferSuccessfully : "Deleted car offer successfully",
  deletedCarSuccessfully : "Deleted car successfully",
  hi : "Hi",
  beitLahiya : "Beit Lahiya",
  beitHanoun : "Beit Hanoun",
  jabalia : "Jabalia",
  gaza : "Gaza",
  nuseirat : "Nuseirat",
  bureij : "Bureij",
  dairAlBalah : "Dair Al Balah",
  khanYounes : "Khan Younes",
  rafah : "Rafah",

  addCarOffer : "add car offer",
  editCarOffer : "edit car offer",
  editCar : "edit car",
  deleteCar : "delete car",
  deleteCarOffer : "delete car offer",
  off : "off",

  phoneEmpty : "this phone Number is empty!",
  emailExists : "This email is already exists",
  emailNotValid : "not valid email",
  phoneNotValid : "not valid phone",
  requiredValue : "This field cannot be empty",

  gmailNotInstalled : "Gmail not installed",
  phoneNotInstalled : "Phone not installed",
  whatsNotInstalled : "WhatsApp not installed",
  whatsNumberEmpty : "WhatsApp number is empty",

  alertExitTitle : "Attention",
  alertExitBody : "Do you want to exit the application?",

  yes : "Yes",
  no : "No",

};