
import 'text_language_keys.dart';

Map<String, String> arabic = {

  signUp : "تسجيل جديد",
  name : "الاسم",
  enterStoreName : "ادخل اسم المتجر",
  phone : "الهاتف",
  enterStorePhoneNumber : "ادخل رقم هاتف المتجر",
  address  : "العنوان",
  enterStoreAddress : "ادخل عنوان المتجر",
  state : "المحافظة",
  choose : "-اختر-",
  thisFieldIsRequired : "هذا الحقل مطلوب",
  facebook : "فيسبوك",
  enterStoreFacebookUrl : "ادخل حساب الفيسبوك",
  instegram : "انستقرام",
  enterStoreInstegramUrl : "ادخل حساب الانستقرام",
  whatsapp : "واتساب",
  enterStoreWhatsappUrl : "ادخل رقم الواتساب",
  registerAccount : "تسجيل حساب",
  signUpWithYourInfo : "سجل مع المعلومات الخاصة بك",
  enterYourName : "ادخل الاسم",
  email : "البريد الالكتروني",
  enterYourEmail : "ادخل البريد الالكتروني",
  enterYourPhoneNumber : "ادخل رقم الهاتف الخاص بك",
  enterYourAddress : "ادخل العنوان الخاص بك",
  password : "كلمة المرور",
  enterYourPassword : "ادخل كلمة المرور",
  confirmPassword : "تأكيد كلمة المرور",
  re_enterYourPassword : "اعد ادخال كلمة المرور",
  imAVendor : "انا بائع",
  signIn : "تسجيل الدخول",
  welcomeBack : "اهلا بكم من جديد",
  signInWithYourEmailAndPassword : "قم بتسجيل الدخول باستخدام بريدك الإلكتروني وكلمة المرور",
  rememberMe : "تذكرني",
  forgetPassword : "نسيت كلمة المرور",
  dontHaveAccount : "ليس لديك حساب ؟",
  titleForgotPassword : "رابطا للعودة الى حسابك\nالرجاء إدخال رقم هاتفك وسنرسل لك",
  Continue : "استمرار",
  otpVerification : "OTP التحقق من",
  weSentYourCodeTo : "أرسلنا رمزك الى",
  thisCodeWillExpiredIn : "ستنتهي صلاحية هذا الرمز في",
  resendOtpCode : "اعد إرسال كود التحقق",
  pleaseEnterYourNewPassword : "الرجاء إدخال كلمة المرور الجديدة",
  enterNewPassword : "ادخل كلمة المرور الجديدة",
  re_enterNewPassword : "اعد إدخال كلمة المرور الجديدة",
  addCar : "إضافة سيارة",
  enterCarName : "ادخل اسم السيارة",
  enterCarPrice : "ادخل سعر السيارة",
  price : "السعر",
  enterCarDescription : "ادخل وصف السيارة",
  description : "الوصف",
  save : "حفظ",
  addOffer : "إضافة عرض",
  oldPrice : "السعر القديم:",
  enterCarNewPrice : "ادخل سعر السيارة الجديد",
  newPrice : "السعر الجديد",
  discountPercentage : "نسبة الخصم:",
  feedback : "التقيمات",
  addYourComment : "أضف تعليقك",
  comment : "تعليق",
  submit : "إرسال",
  callTheStore : "اتصل بالمتجر",
  updateCar : "تحديث السيارة",
  Update : "تحديث",
  updateOffer : "تحديث العرض",
  updateStore : "تحديث المتجر",
  language : "اللغة",
  chooseLang: "اختر اللغة",
  ar: "العربية",
  en: "الانجليزية",
  helpCenter : "مركز المساعدة",
  faq : "التعليمات",
  helpCenter1 : "كيف يعمل الضمان في المتجر ؟",
  helpCenter2 : "ما هي مدة تسليم طلبي ؟",
  helpCenter3 : "كيف تصبح بائع متجر ؟",
  helpCenter4 : " لماذا لا أقبل  OTP على هاتفي؟",
  helpCenter5 : " كيف أقيم طلبي المنتجات؟",
  contactUs : "اتصل بنا",
  chatUsNow : "دردش معنا الآن",
  chatHere : "يمكنك الدردشة معنا هنا",
  profile : "الملف الشخصي",
  enterNewName : "ادخل الاسم الجديد",
  enterNewEmail : "ادخل البريد الالكتروني الجديد",
  enterNewPhoneNumber : "ادخل رقم الهاتف الجديد",
  enterNewAddress : "ادخل العنوان الجديد",
  saveChanges : "حفظ التغيرات",
  cars : "السيارات",
  rateStore : "تقييم المتجر",
  favorites : "المفضلة",
  bestSeller : "أفضل بائعون",
  newCars : "السيارات الجديدة",
  offers : "العروض",
  searchCars : "البحث عن السيارات",
  titleSearchCars : "يمكنك البحث عن أي سيارة",
  searchCarsAndStores : "يمكنك البحث عن السيارات والمتاجر",
  settings : "الإعدادات",
  myAccount : "حسابي",
  myStore : "متجري",
  logOut : "تسجيل الخروج",
  chooseImagesForCar : "الرجاء اختيار الصور للسيارة",
  deletedOfferSuccessfully : "تم حذف العرض بنجاح",
  emailNotFound : "البريد الإلكتروني غير موجود !!",
  emailOrPasswordNotCorrect : "البريد الإلكتروني أو كلمة المرور غير صحيحة",
  otpNumberIsNotCorrect : "  رقم OTP غير صحيح !",
  otpNumberExpired : "!!OTP انتهت صلاحية رقم",
  blockedAllRequests : "لقد حظرنا جميع الطلبات الواردة من هذا الجهاز بسبب نشاط غير عادي",
  passwordAndRePasswordNotMatched : "كلمة المرور وإعادة كلمة المرور غير متطابقتين !",
  chooseLogoForStore : "الرجاء اختيار شعار المتجر",
  thisLinkIsEmpty : "هذا الرابط فارغ !",
  deletedCarOfferSuccessfully : "تم حذف عرض السيارة بنجاح",
  deletedCarSuccessfully : "تم حذف السيارة بنجاح",
  hi : "مرحبا",
  beitLahiya : "بيت لاهيا",
  beitHanoun : "بيت حانون",
  jabalia : "جباليا",
  gaza : "غزة",
  nuseirat : "النصيرات",
  bureij : "البريج",
  dairAlBalah : "دير البلح",
  khanYounes : "خانيونس",
  rafah : "رفح",

  addCarOffer : "إضافة عرض للسيارة",
  editCarOffer : "تعديل عرض السيارة",
  editCar : "تحرير السيارة",
  deleteCar : "حذف السيارة",
  deleteCarOffer : "حذف عرض السيارة",
  off : "خصم",

  phoneEmpty : "رقم الهاتف هذا فارغ!",
  emailExists : "هذا البريد الإلكتروني موجود بالفعل",
  emailNotValid : "بريد إلكتروني غير صالح",
  phoneNotValid : "هاتف غير صالح",
  requiredValue : "هذا الحقل لا يمكن ان يكون فارغا",

  gmailNotInstalled : "جيميل غير مثبت",
  phoneNotInstalled : "الاتصال غير مثبت",
  whatsNotInstalled : "واتساب غير مثبت",
  whatsNumberEmpty : "رقم واتساب فارغ",

  alertExitTitle : "تنبيه",
  alertExitBody : "هل تريد الخروج من التطبيق؟",

  yes : "نعم",
  no : "لا",
};